title: PSAK 2020
baseurl: "/psak_2020" 
url: "http://hegyhati.github.io" 


# Build settings
markdown: kramdown

collections:
  presentations:
    output: true
    presenter: true
    title: true
    id: true
    sort_by: presenter 

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "presentations" 
    values:
      layout: "presentation" 

letsmeeturl: "https://letsmeet.sze.hu/psak"
